/**
 * Schedule-shape classifiers — two small neural networks.
 *
 * WHY a net when there is already a rule parser:
 *
 * The rule parser in scheduleAssistant.ts stays authoritative for building the
 * actual UAC fields, because field generation must be exact and auditable — a
 * probabilistic model has no business deciding whether timeInterval is 5 or 15.
 *
 * What the nets add is an independent second opinion on the *shape* of the
 * request. When the rules and the nets disagree confidently, the phrasing is
 * unusual and the Copilot says so, instead of quietly emitting a schedule the
 * user did not intend. That is exactly the bug that shipped once already, where
 * an interval silently dropped its day restriction.
 *
 * WHY TWO HEADS:
 *
 * A schedule request has two independent dimensions — when in the day it fires,
 * and which days it fires on. "Every 5 minutes on Monday and Tuesday" is both
 * an interval AND a specific-days pattern. A single-label classifier has to
 * pick one, which makes its output ambiguous and produced false disagreements
 * against a rule parse that had correctly captured both. Modelling the two
 * dimensions separately matches the domain and removes the ambiguity.
 *
 * Training data is generated by combining a time phrase with a day phrase, so
 * the two dimensions vary independently and the corpus covers combinations no
 * single template could.
 */
import { MLP } from './models';
import { features, Vocabulary, vectorise, prng, normalise, FeatureOptions, evaluate, EvalResult } from './core';
import { learnedScheduleSamples } from './corpus';
import { weights, ScheduleWeights } from './weights';

/** When in the day the trigger fires. */
export type TimeShape = 'interval' | 'absolute';
/** Which days it fires on. */
export type DayShape =
  | 'daily' | 'businessDays' | 'specificDays'
  | 'monthlyDay' | 'monthlyOrdinal' | 'everyNDays';

export const TIME_SHAPES: TimeShape[] = ['interval', 'absolute'];
export const DAY_SHAPES: DayShape[] = [
  'daily', 'businessDays', 'specificDays', 'monthlyDay', 'monthlyOrdinal', 'everyNDays',
];

const FEATS: FeatureOptions = {
  wordNGrams: [1, 2],
  charNGrams: [3, 4],
  dropStop: false,   // "every", "on", "of" are signal here, not noise
  shape: true,
};

// ── Corpus generation ────────────────────────────────────────────────────────

const pick = <T>(r: () => number, xs: T[]): T => xs[Math.floor(r() * xs.length)];

const FULL_DAYS = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'];
const SHORT_DAYS = ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'];
const PLURAL_DAYS = FULL_DAYS.map(d => d + 's');
const ZONES = ['', ' UTC', ' Asia/Kolkata', ' America/New_York', ' IST', ' EST', ' Europe/London'];
const CLOCKS = ['8pm', '06:30', '0900', 'midnight', '5 am', '22:00', 'noon', '7:15am', '1800'];

/** A phrase for the time dimension, plus its label. */
function timePhrase(r: () => number): { text: string; label: TimeShape } {
  if (r() < 0.5) {
    const n = pick(r, [2, 3, 5, 10, 15, 20, 30, 45, 60, 90]);
    const unit = pick(r, ['minutes', 'mins', 'minute', 'hours', 'hrs', 'hour', 'seconds', 'secs']);
    let text = `every ${n} ${unit}`;
    if (r() < 0.30) text += ` from ${pick(r, CLOCKS)} to ${pick(r, CLOCKS)}`;
    else if (r() < 0.15) text += ` between ${pick(r, CLOCKS)} and ${pick(r, CLOCKS)}`;
    else if (r() < 0.12) text += ` until ${pick(r, CLOCKS)}`;
    // Bare interval words, which carry no number.
    if (r() < 0.10) text = pick(r, ['hourly', 'every half an hour', 'every other hour', 'every 30 mins']);
    return { text, label: 'interval' };
  }
  // Absolute: a fixed time of day, or none stated at all.
  const t = r() < 0.82 ? `at ${pick(r, CLOCKS)}` : '';
  return { text: t, label: 'absolute' };
}

/** A phrase for the day dimension, plus its label. */
function dayPhrase(r: () => number): { text: string; label: DayShape } {
  const kind = pick(r, DAY_SHAPES);
  switch (kind) {
    case 'daily':
      return { text: pick(r, ['daily', 'every day', 'each day', 'everyday', 'every night', 'every morning', 'once a day', '']), label: 'daily' };

    case 'businessDays':
      return { text: pick(r, ['weekdays', 'every weekday', 'on weekdays', 'business days only', 'only on business days', 'monday to friday', 'mon-fri', 'on working days', 'weekdays only']), label: 'businessDays' };

    case 'specificDays': {
      if (r() < 0.14) return { text: pick(r, ['at the weekend', 'weekends only', 'on weekends']), label: 'specificDays' };
      // Plural forms are how this is usually said out loud — "on tuesdays and
      // thursdays" — and were absent from the corpus, so the classifier had only
      // the singular to go on.
      const roll = r();
      const pool = roll < 0.4 ? FULL_DAYS : roll < 0.7 ? SHORT_DAYS : PLURAL_DAYS;
      const k = 1 + Math.floor(r() * 3);
      const days: string[] = [];
      while (days.length < k) {
        const d = pick(r, pool);
        if (!days.includes(d)) days.push(d);
      }
      const joined = r() < 0.4 ? days.join(', ')
        : r() < 0.7 ? days.join(' and ')
          : days.join(', ').replace(/, ([^,]*)$/, ' and $1');
      const lead = pick(r, ['every ', 'on ', 'of ', '']);
      return { text: `${lead}${joined}`, label: 'specificDays' };
    }

    case 'monthlyDay': {
      const d = 1 + Math.floor(r() * 28);
      const sfx = d % 10 === 1 && d !== 11 ? 'st' : d % 10 === 2 && d !== 12 ? 'nd' : d % 10 === 3 && d !== 13 ? 'rd' : 'th';
      return {
        text: pick(r, [
          `on the ${d}${sfx} of every month`, `monthly on day ${d}`,
          `the ${d}${sfx} of each month`, `day ${d} every month`, 'monthly',
        ]),
        label: 'monthlyDay',
      };
    }

    case 'monthlyOrdinal': {
      const ord = pick(r, ['first', 'second', 'third', 'fourth', 'last']);
      const noun = r() < 0.65 ? pick(r, FULL_DAYS) : pick(r, ['business day', 'working day', 'day']);
      return {
        text: pick(r, [
          `the ${ord} ${noun} of every month`, `${ord} ${noun} of the month`,
          `on the ${ord} ${noun} each month`,
        ]),
        label: 'monthlyOrdinal',
      };
    }

    case 'everyNDays': {
      const n = pick(r, [2, 3, 4, 5, 6, 7, 10, 14, 21]);
      return {
        text: pick(r, [
          `every ${n} days`, `every ${n} days starting 2026-08-01`,
          'every other day', 'every 2 weeks', 'biweekly', 'fortnightly',
        ]),
        label: 'everyNDays',
      };
    }
  }
}

export interface Sample { text: string; time: TimeShape; day: DayShape }

/**
 * Deterministically generates the corpus by pairing a time phrase with a day
 * phrase. Word order is varied because users put them in either order.
 */
function generateCorpus(count = 2600, seed = 91750): Sample[] {
  const r = prng(seed);
  const out: Sample[] = [];
  for (let i = 0; i < count; i++) {
    const t = timePhrase(r);
    const d = dayPhrase(r);
    const zone = r() < 0.3 ? pick(r, ZONES) : '';
    const parts = r() < 0.6 ? [t.text, d.text] : [d.text, t.text];
    const text = (parts.filter(Boolean).join(' ') + zone).trim();
    if (!text) continue;   // both dimensions empty says nothing
    out.push({ text, time: t.label, day: d.label });
  }
  return out;
}

/**
 * The fixed held-out split: the tail of the generated corpus.
 *
 * Held constant on purpose. Learned samples are only ever added to the training
 * side, so held-out accuracy stays comparable across training iterations — a
 * moving test set would make the iteration-to-iteration delta meaningless. The
 * loop measures generalisation separately, against freshly generated job rows
 * from a seed the model has never been trained on.
 */
function splitCorpus(): { train: Sample[]; heldOut: Sample[] } {
  const corpus = generateCorpus();
  const at = Math.floor(corpus.length * 0.85);
  return { train: corpus.slice(0, at), heldOut: corpus.slice(at) };
}

/**
 * The held-out phrases, for the freeze step's guard set.
 *
 * These are measured on rather than fitted to, which is what makes them worth
 * protecting against a runtime update.
 */
export function heldOutShapeSamples(): Sample[] {
  return splitCorpus().heldOut;
}

/**
 * Discards the loaded nets so the next call rebuilds them.
 *
 * Two callers. The freeze step, which must train from the corpus rather than
 * re-freeze an existing artifact. And the runtime learner, which uses it to throw
 * away accumulated gradient steps and return to the shipped weights — clearing
 * the correction store alone would not do that, because the steps were applied to
 * the networks in memory.
 */
export function resetSchedulePattern(): void {
  trained = null;
}

// ── Training ─────────────────────────────────────────────────────────────────

interface Trained {
  timeNet: MLP;
  dayNet: MLP;
  vocab: Vocabulary;
  timeTrain: number; timeHeldOut: number;
  dayTrain: number; dayHeldOut: number;
  corpusSize: number;
  generatedSamples: number;
  learnedSamples: number;
  epochs: number;
  trainMs: number;
}

let trained: Trained | null = null;
const EPOCHS = 70;

/** Where the current weights came from, for the health endpoint. */
let source: 'frozen' | 'trained' = 'trained';

/** Rebuilds the nets from the shipped artifact, or null if it is unusable. */
function fromFrozen(): Trained | null {
  const w = weights();
  if (!w?.schedule) return null;
  const s: ScheduleWeights = w.schedule;
  // The artifact carries its own label order. Reading it rather than assuming
  // ours matches means a reordered enum is caught here instead of quietly
  // relabelling every prediction.
  if (s.timeShapes.join(',') !== TIME_SHAPES.join(',')) return null;
  if (s.dayShapes.join(',') !== DAY_SHAPES.join(',')) return null;

  const t0 = Date.now();
  const vocab = Vocabulary.fromTerms(s.vocabulary);
  const timeNet = MLP.fromJSON(s.timeNet);
  const dayNet = MLP.fromJSON(s.dayNet);
  source = 'frozen';
  return {
    timeNet, dayNet, vocab,
    timeTrain: s.accuracy.timeTrain, timeHeldOut: s.accuracy.timeHeldOut,
    dayTrain: s.accuracy.dayTrain, dayHeldOut: s.accuracy.dayHeldOut,
    corpusSize: s.corpus.generated + s.corpus.learned,
    generatedSamples: s.corpus.generated,
    learnedSamples: s.corpus.learned,
    epochs: s.epochs,
    trainMs: Date.now() - t0,
  };
}

function ensure(): Trained {
  if (trained) return trained;

  const frozen = fromFrozen();
  if (frozen) { trained = frozen; return trained; }

  source = 'trained';
  const t0 = Date.now();

  const { train: generated, heldOut: testSet } = splitCorpus();

  // Learned samples join the training side only, so the held-out split stays a
  // set of phrases the model was never fitted to.
  const learned: Sample[] = learnedScheduleSamples().map(s => ({ text: s.text, time: s.time, day: s.day }));
  const trainSet = [...generated, ...learned];

  // Vocabulary from the training split only — never the test split.
  const vocab = new Vocabulary();
  const bags = trainSet.map(s => features(s.text, FEATS));
  for (const b of bags) for (const f of b.keys()) vocab.add(f);

  // Unit-normalise. Raw counts make a vector's magnitude scale with phrase
  // length, so a long phrase yields a far larger gradient than a short one for
  // no good reason. Unnormalised, the first epoch drove the hidden biases
  // negative and the entire ReLU layer died, collapsing the net to class priors.
  const X = bags.map(b => normalise(vectorise(b, vocab)));

  const timeNet = new MLP({
    inputSize: vocab.size, hiddenSize: 16, outputSize: TIME_SHAPES.length,
    epochs: EPOCHS, learningRate: 0.3, momentum: 0.9, l2: 1e-5, seed: 20260731,
  });
  timeNet.train(X, trainSet.map(s => TIME_SHAPES.indexOf(s.time)));

  const dayNet = new MLP({
    inputSize: vocab.size, hiddenSize: 32, outputSize: DAY_SHAPES.length,
    epochs: EPOCHS, learningRate: 0.3, momentum: 0.9, l2: 1e-5, seed: 20260809,
  });
  dayNet.train(X, trainSet.map(s => DAY_SHAPES.indexOf(s.day)));

  trained = {
    timeNet, dayNet, vocab,
    timeTrain: 0, timeHeldOut: 0, dayTrain: 0, dayHeldOut: 0,
    corpusSize: trainSet.length + testSet.length,
    generatedSamples: generated.length + testSet.length,
    learnedSamples: learned.length,
    epochs: EPOCHS, trainMs: Date.now() - t0,
  };

  trained.timeTrain = evaluate(trainSet.map(s => ({ text: s.text, label: s.time })), t => classifyShape(t).time).accuracy;
  trained.timeHeldOut = evaluate(testSet.map(s => ({ text: s.text, label: s.time })), t => classifyShape(t).time).accuracy;
  trained.dayTrain = evaluate(trainSet.map(s => ({ text: s.text, label: s.day })), t => classifyShape(t).day).accuracy;
  trained.dayHeldOut = evaluate(testSet.map(s => ({ text: s.text, label: s.day })), t => classifyShape(t).day).accuracy;

  return trained;
}

export interface ShapePrediction {
  time: TimeShape;
  timeConfidence: number;
  day: DayShape;
  dayConfidence: number;
}

export function classifyShape(text: string): ShapePrediction {
  const t = ensure();
  // Must match the training-time transform exactly.
  const v = normalise(vectorise(features(text, FEATS), t.vocab));
  const tp = t.timeNet.predict(v);
  const dp = t.dayNet.predict(v);
  return {
    time: TIME_SHAPES[tp.index],
    timeConfidence: tp.confidence,
    day: DAY_SHAPES[dp.index],
    dayConfidence: dp.confidence,
  };
}

/**
 * Confidence a disagreement must clear before it is raised with the user.
 *
 * These nets fit their generated corpus almost perfectly, so their softmax
 * outputs are sharp and poorly calibrated on text unlike the corpus. The floor
 * is therefore set high, and the rule parser — not the net — always decides the
 * fields. The net's only job is to raise a hand.
 */
export const DISAGREEMENT_FLOOR = 0.90;

/** Everything the freeze step needs to write an artifact. */
export function exportScheduleWeights(): ScheduleWeights {
  const t = ensure();
  return {
    vocabulary: t.vocab.toTerms(),
    timeShapes: [...TIME_SHAPES],
    dayShapes: [...DAY_SHAPES],
    timeNet: t.timeNet.toJSON(),
    dayNet: t.dayNet.toJSON(),
    corpus: { generated: t.generatedSamples, learned: t.learnedSamples },
    accuracy: {
      timeTrain: Number(t.timeTrain.toFixed(6)),
      timeHeldOut: Number(t.timeHeldOut.toFixed(6)),
      dayTrain: Number(t.dayTrain.toFixed(6)),
      dayHeldOut: Number(t.dayHeldOut.toFixed(6)),
    },
    epochs: t.epochs,
  };
}

/** The live nets, for the online learner. */
export function scheduleNets(): { timeNet: MLP; dayNet: MLP; vocab: Vocabulary } {
  const t = ensure();
  return { timeNet: t.timeNet, dayNet: t.dayNet, vocab: t.vocab };
}

/** Feature vector for text, in exactly the form the nets were trained on. */
export function shapeVector(text: string, vocab: Vocabulary): Float64Array {
  return normalise(vectorise(features(text, FEATS), vocab));
}

export function schedulePatternStats() {
  const t = ensure();
  return {
    algorithm: 'Two multi-layer perceptrons (1 hidden layer, leaky ReLU, softmax)',
    weightSource: source === 'frozen'
      ? 'frozen artifact — no training at boot'
      : 'trained in-process from the repository corpus',
    rationale: 'time-of-day and day-of-week are independent dimensions; one label per dimension',
    features: 'word 1-2 grams + char 3-4 grams + shape, unit-normalised',
    inputs: t.vocab.size,
    timeHead: { hidden: 16, classes: TIME_SHAPES.length, parameters: t.timeNet.parameterCount },
    dayHead: { hidden: 32, classes: DAY_SHAPES.length, parameters: t.dayNet.parameterCount },
    epochs: t.epochs,
    trainingExamples: t.corpusSize,
    corpus: {
      generated: t.generatedSamples,
      learned: t.learnedSamples,
    },
    trainMs: t.trainMs,
    timeAccuracy: { train: Number(t.timeTrain.toFixed(4)), heldOut: Number(t.timeHeldOut.toFixed(4)) },
    dayAccuracy: { train: Number(t.dayTrain.toFixed(4)), heldOut: Number(t.dayHeldOut.toFixed(4)) },
    finalLoss: {
      time: Number(t.timeNet.finalLoss.toFixed(4)),
      day: Number(t.dayNet.finalLoss.toFixed(4)),
    },
  };
}

export function evaluateShapes(): {
  time: { train: EvalResult; heldOut: EvalResult };
  day: { train: EvalResult; heldOut: EvalResult };
} {
  ensure();
  const { train: tr, heldOut: te } = splitCorpus();
  return {
    time: {
      train: evaluate(tr.map(s => ({ text: s.text, label: s.time })), t => classifyShape(t).time),
      heldOut: evaluate(te.map(s => ({ text: s.text, label: s.time })), t => classifyShape(t).time),
    },
    day: {
      train: evaluate(tr.map(s => ({ text: s.text, label: s.day })), t => classifyShape(t).day),
      heldOut: evaluate(te.map(s => ({ text: s.text, label: s.day })), t => classifyShape(t).day),
    },
  };
}
