/**
 * Schedule-shape classifiers — two small neural networks.
 *
 * WHY a net when there is already a rule parser:
 *
 * The rule parser in scheduleAssistant.ts stays authoritative for building the
 * actual UAC fields, because field generation must be exact and auditable — a
 * probabilistic model has no business deciding whether timeInterval is 5 or 15.
 *
 * What the nets add is an independent second opinion on the *shape* of the
 * request. When the rules and the nets disagree confidently, the phrasing is
 * unusual and the Copilot says so, instead of quietly emitting a schedule the
 * user did not intend. That is exactly the bug that shipped once already, where
 * an interval silently dropped its day restriction.
 *
 * WHY TWO HEADS:
 *
 * A schedule request has two independent dimensions — when in the day it fires,
 * and which days it fires on. "Every 5 minutes on Monday and Tuesday" is both
 * an interval AND a specific-days pattern. A single-label classifier has to
 * pick one, which makes its output ambiguous and produced false disagreements
 * against a rule parse that had correctly captured both. Modelling the two
 * dimensions separately matches the domain and removes the ambiguity.
 *
 * Training data is generated by combining a time phrase with a day phrase, so
 * the two dimensions vary independently and the corpus covers combinations no
 * single template could.
 */
import { MLP } from './models';
import { features, Vocabulary, vectorise, prng, normalise, FeatureOptions, evaluate, EvalResult } from './core';

/** When in the day the trigger fires. */
export type TimeShape = 'interval' | 'absolute';
/** Which days it fires on. */
export type DayShape =
  | 'daily' | 'businessDays' | 'specificDays'
  | 'monthlyDay' | 'monthlyOrdinal' | 'everyNDays';

export const TIME_SHAPES: TimeShape[] = ['interval', 'absolute'];
export const DAY_SHAPES: DayShape[] = [
  'daily', 'businessDays', 'specificDays', 'monthlyDay', 'monthlyOrdinal', 'everyNDays',
];

const FEATS: FeatureOptions = {
  wordNGrams: [1, 2],
  charNGrams: [3, 4],
  dropStop: false,   // "every", "on", "of" are signal here, not noise
  shape: true,
};

// ── Corpus generation ────────────────────────────────────────────────────────

const pick = <T>(r: () => number, xs: T[]): T => xs[Math.floor(r() * xs.length)];

const FULL_DAYS = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'];
const SHORT_DAYS = ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'];
const ZONES = ['', ' UTC', ' Asia/Kolkata', ' America/New_York', ' IST', ' EST', ' Europe/London'];
const CLOCKS = ['8pm', '06:30', '0900', 'midnight', '5 am', '22:00', 'noon', '7:15am', '1800'];

/** A phrase for the time dimension, plus its label. */
function timePhrase(r: () => number): { text: string; label: TimeShape } {
  if (r() < 0.5) {
    const n = pick(r, [2, 3, 5, 10, 15, 20, 30, 45, 60, 90]);
    const unit = pick(r, ['minutes', 'mins', 'minute', 'hours', 'hrs', 'hour', 'seconds', 'secs']);
    let text = `every ${n} ${unit}`;
    if (r() < 0.30) text += ` from ${pick(r, CLOCKS)} to ${pick(r, CLOCKS)}`;
    else if (r() < 0.15) text += ` between ${pick(r, CLOCKS)} and ${pick(r, CLOCKS)}`;
    else if (r() < 0.12) text += ` until ${pick(r, CLOCKS)}`;
    // Bare interval words, which carry no number.
    if (r() < 0.10) text = pick(r, ['hourly', 'every half an hour', 'every other hour', 'every 30 mins']);
    return { text, label: 'interval' };
  }
  // Absolute: a fixed time of day, or none stated at all.
  const t = r() < 0.82 ? `at ${pick(r, CLOCKS)}` : '';
  return { text: t, label: 'absolute' };
}

/** A phrase for the day dimension, plus its label. */
function dayPhrase(r: () => number): { text: string; label: DayShape } {
  const kind = pick(r, DAY_SHAPES);
  switch (kind) {
    case 'daily':
      return { text: pick(r, ['daily', 'every day', 'each day', 'everyday', 'every night', 'every morning', 'once a day', '']), label: 'daily' };

    case 'businessDays':
      return { text: pick(r, ['weekdays', 'every weekday', 'on weekdays', 'business days only', 'only on business days', 'monday to friday', 'mon-fri', 'on working days', 'weekdays only']), label: 'businessDays' };

    case 'specificDays': {
      if (r() < 0.14) return { text: pick(r, ['at the weekend', 'weekends only', 'on weekends']), label: 'specificDays' };
      const pool = r() < 0.5 ? FULL_DAYS : SHORT_DAYS;
      const k = 1 + Math.floor(r() * 3);
      const days: string[] = [];
      while (days.length < k) {
        const d = pick(r, pool);
        if (!days.includes(d)) days.push(d);
      }
      const joined = r() < 0.4 ? days.join(', ')
        : r() < 0.7 ? days.join(' and ')
          : days.join(', ').replace(/, ([^,]*)$/, ' and $1');
      const lead = pick(r, ['every ', 'on ', 'of ', '']);
      return { text: `${lead}${joined}`, label: 'specificDays' };
    }

    case 'monthlyDay': {
      const d = 1 + Math.floor(r() * 28);
      const sfx = d % 10 === 1 && d !== 11 ? 'st' : d % 10 === 2 && d !== 12 ? 'nd' : d % 10 === 3 && d !== 13 ? 'rd' : 'th';
      return {
        text: pick(r, [
          `on the ${d}${sfx} of every month`, `monthly on day ${d}`,
          `the ${d}${sfx} of each month`, `day ${d} every month`, 'monthly',
        ]),
        label: 'monthlyDay',
      };
    }

    case 'monthlyOrdinal': {
      const ord = pick(r, ['first', 'second', 'third', 'fourth', 'last']);
      const noun = r() < 0.65 ? pick(r, FULL_DAYS) : pick(r, ['business day', 'working day', 'day']);
      return {
        text: pick(r, [
          `the ${ord} ${noun} of every month`, `${ord} ${noun} of the month`,
          `on the ${ord} ${noun} each month`,
        ]),
        label: 'monthlyOrdinal',
      };
    }

    case 'everyNDays': {
      const n = pick(r, [2, 3, 4, 5, 6, 7, 10, 14, 21]);
      return {
        text: pick(r, [
          `every ${n} days`, `every ${n} days starting 2026-08-01`,
          'every other day', 'every 2 weeks', 'biweekly', 'fortnightly',
        ]),
        label: 'everyNDays',
      };
    }
  }
}

interface Sample { text: string; time: TimeShape; day: DayShape }

/**
 * Deterministically generates the corpus by pairing a time phrase with a day
 * phrase. Word order is varied because users put them in either order.
 */
function generateCorpus(count = 2600, seed = 91750): Sample[] {
  const r = prng(seed);
  const out: Sample[] = [];
  for (let i = 0; i < count; i++) {
    const t = timePhrase(r);
    const d = dayPhrase(r);
    const zone = r() < 0.3 ? pick(r, ZONES) : '';
    const parts = r() < 0.6 ? [t.text, d.text] : [d.text, t.text];
    const text = (parts.filter(Boolean).join(' ') + zone).trim();
    if (!text) continue;   // both dimensions empty says nothing
    out.push({ text, time: t.label, day: d.label });
  }
  return out;
}

// ── Training ─────────────────────────────────────────────────────────────────

interface Trained {
  timeNet: MLP;
  dayNet: MLP;
  vocab: Vocabulary;
  timeTrain: number; timeHeldOut: number;
  dayTrain: number; dayHeldOut: number;
  corpusSize: number;
  epochs: number;
  trainMs: number;
}

let trained: Trained | null = null;
const EPOCHS = 70;

function ensure(): Trained {
  if (trained) return trained;
  const t0 = Date.now();

  const corpus = generateCorpus();
  const split = Math.floor(corpus.length * 0.85);
  const trainSet = corpus.slice(0, split);
  const testSet = corpus.slice(split);

  // Vocabulary from the training split only — never the test split.
  const vocab = new Vocabulary();
  const bags = trainSet.map(s => features(s.text, FEATS));
  for (const b of bags) for (const f of b.keys()) vocab.add(f);

  // Unit-normalise. Raw counts make a vector's magnitude scale with phrase
  // length, so a long phrase yields a far larger gradient than a short one for
  // no good reason. Unnormalised, the first epoch drove the hidden biases
  // negative and the entire ReLU layer died, collapsing the net to class priors.
  const X = bags.map(b => normalise(vectorise(b, vocab)));

  const timeNet = new MLP({
    inputSize: vocab.size, hiddenSize: 16, outputSize: TIME_SHAPES.length,
    epochs: EPOCHS, learningRate: 0.3, momentum: 0.9, l2: 1e-5, seed: 20260731,
  });
  timeNet.train(X, trainSet.map(s => TIME_SHAPES.indexOf(s.time)));

  const dayNet = new MLP({
    inputSize: vocab.size, hiddenSize: 32, outputSize: DAY_SHAPES.length,
    epochs: EPOCHS, learningRate: 0.3, momentum: 0.9, l2: 1e-5, seed: 20260809,
  });
  dayNet.train(X, trainSet.map(s => DAY_SHAPES.indexOf(s.day)));

  trained = {
    timeNet, dayNet, vocab,
    timeTrain: 0, timeHeldOut: 0, dayTrain: 0, dayHeldOut: 0,
    corpusSize: corpus.length, epochs: EPOCHS, trainMs: Date.now() - t0,
  };

  trained.timeTrain = evaluate(trainSet.map(s => ({ text: s.text, label: s.time })), t => classifyShape(t).time).accuracy;
  trained.timeHeldOut = evaluate(testSet.map(s => ({ text: s.text, label: s.time })), t => classifyShape(t).time).accuracy;
  trained.dayTrain = evaluate(trainSet.map(s => ({ text: s.text, label: s.day })), t => classifyShape(t).day).accuracy;
  trained.dayHeldOut = evaluate(testSet.map(s => ({ text: s.text, label: s.day })), t => classifyShape(t).day).accuracy;

  return trained;
}

export interface ShapePrediction {
  time: TimeShape;
  timeConfidence: number;
  day: DayShape;
  dayConfidence: number;
}

export function classifyShape(text: string): ShapePrediction {
  const t = ensure();
  // Must match the training-time transform exactly.
  const v = normalise(vectorise(features(text, FEATS), t.vocab));
  const tp = t.timeNet.predict(v);
  const dp = t.dayNet.predict(v);
  return {
    time: TIME_SHAPES[tp.index],
    timeConfidence: tp.confidence,
    day: DAY_SHAPES[dp.index],
    dayConfidence: dp.confidence,
  };
}

/**
 * Confidence a disagreement must clear before it is raised with the user.
 *
 * These nets fit their generated corpus almost perfectly, so their softmax
 * outputs are sharp and poorly calibrated on text unlike the corpus. The floor
 * is therefore set high, and the rule parser — not the net — always decides the
 * fields. The net's only job is to raise a hand.
 */
export const DISAGREEMENT_FLOOR = 0.90;

export function schedulePatternStats() {
  const t = ensure();
  return {
    algorithm: 'Two multi-layer perceptrons (1 hidden layer, leaky ReLU, softmax)',
    rationale: 'time-of-day and day-of-week are independent dimensions; one label per dimension',
    features: 'word 1-2 grams + char 3-4 grams + shape, unit-normalised',
    inputs: t.vocab.size,
    timeHead: { hidden: 16, classes: TIME_SHAPES.length, parameters: t.timeNet.parameterCount },
    dayHead: { hidden: 32, classes: DAY_SHAPES.length, parameters: t.dayNet.parameterCount },
    epochs: t.epochs,
    trainingExamples: t.corpusSize,
    trainMs: t.trainMs,
    timeAccuracy: { train: Number(t.timeTrain.toFixed(4)), heldOut: Number(t.timeHeldOut.toFixed(4)) },
    dayAccuracy: { train: Number(t.dayTrain.toFixed(4)), heldOut: Number(t.dayHeldOut.toFixed(4)) },
    finalLoss: {
      time: Number(t.timeNet.finalLoss.toFixed(4)),
      day: Number(t.dayNet.finalLoss.toFixed(4)),
    },
  };
}

export function evaluateShapes(): {
  time: { train: EvalResult; heldOut: EvalResult };
  day: { train: EvalResult; heldOut: EvalResult };
} {
  ensure();
  const corpus = generateCorpus();
  const split = Math.floor(corpus.length * 0.85);
  const tr = corpus.slice(0, split), te = corpus.slice(split);
  return {
    time: {
      train: evaluate(tr.map(s => ({ text: s.text, label: s.time })), t => classifyShape(t).time),
      heldOut: evaluate(te.map(s => ({ text: s.text, label: s.time })), t => classifyShape(t).time),
    },
    day: {
      train: evaluate(tr.map(s => ({ text: s.text, label: s.day })), t => classifyShape(t).day),
      heldOut: evaluate(te.map(s => ({ text: s.text, label: s.day })), t => classifyShape(t).day),
    },
  };
}
