/**
 * UAC REST schema knowledge, derived from the controller's own OpenAPI spec.
 *
 * The artifact this loads is generated by backend/scripts/extract-uac-schema.cjs
 * from openapi.json. The full spec is 1.2 MB and gitignored, so it will not be
 * present in a fresh clone; the distilled artifact is committed instead, which
 * keeps this capability working everywhere and makes controller upgrades an
 * explicit, reviewable regeneration step.
 *
 * This is the authoritative answer to "is this a real UAC field?" — more
 * authoritative than our own allow-lists, which were written by hand. The
 * cross-check below compares the two and is what turns the spec into a bug
 * finder rather than decoration.
 */
import { ALLOWED_TASK_FIELDS, ALLOWED_TRIGGER_FIELDS } from '../../utils/payloadMapper';
import { KnowledgeChunk } from '../types';
import raw from './uacSchema.generated.json';

interface TypeInfo {
  schema: string;
  inherits: string[];
  fields: string[];
  types: Record<string, string>;
  enums: Record<string, string[]>;
}

interface SchemaArtifact {
  source: string;
  api: string;
  controllerVersion: string;
  openapi: string;
  extractedAt: string;
  endpoints: { path: string; methods: string[] }[];
  tasks: Record<string, TypeInfo>;
  triggers: Record<string, TypeInfo>;
}

export const UAC_SCHEMA = raw as unknown as SchemaArtifact;

export const CONTROLLER_VERSION = UAC_SCHEMA.controllerVersion;

/** Field names the controller accepts for a task type, or [] if unknown. */
export function taskFields(taskType: string): string[] {
  return UAC_SCHEMA.tasks[taskType]?.fields ?? [];
}

/** Field names the controller accepts for a trigger type, or [] if unknown. */
export function triggerFields(triggerType: string): string[] {
  return UAC_SCHEMA.triggers[triggerType]?.fields ?? [];
}

export function knownTaskTypes(): string[] {
  return Object.keys(UAC_SCHEMA.tasks);
}

export function knownTriggerTypes(): string[] {
  return Object.keys(UAC_SCHEMA.triggers);
}

/** Every field name valid on at least one task type. */
const ALL_TASK_FIELDS = new Set<string>(
  Object.values(UAC_SCHEMA.tasks).flatMap(t => t.fields),
);
/** Every field name valid on at least one trigger type. */
const ALL_TRIGGER_FIELDS = new Set<string>(
  Object.values(UAC_SCHEMA.triggers).flatMap(t => t.fields),
);

export function isRealTaskField(name: string): boolean { return ALL_TASK_FIELDS.has(name); }
export function isRealTriggerField(name: string): boolean { return ALL_TRIGGER_FIELDS.has(name); }

/** Which task types accept a given field. Useful for explaining a rejection. */
export function taskTypesAccepting(field: string): string[] {
  return Object.entries(UAC_SCHEMA.tasks)
    .filter(([, t]) => t.fields.includes(field))
    .map(([k]) => k);
}

// ── Allow-list cross-check ───────────────────────────────────────────────────

export interface CrossCheck {
  /** In our allow-list but on no schema in the spec — likely a typo or removed field. */
  notInSpec: string[];
  /** In the spec but not on our allow-list — silently dropped from payloads today. */
  notAllowed: string[];
  allowedCount: number;
  specCount: number;
}

/**
 * Compares our hand-written allow-lists against the controller spec.
 *
 * Two failure modes it catches:
 *  - a field we allow that the controller does not know, which is silently
 *    dropped by UAC or rejected outright;
 *  - a real controller field we do not allow, which filterPayload strips before
 *    the request is sent — so a user filling that spreadsheet column would see
 *    the value vanish with no explanation.
 */
export function crossCheckTaskFields(): CrossCheck {
  const allowed = [...ALLOWED_TASK_FIELDS];
  return {
    notInSpec: allowed.filter(f => !ALL_TASK_FIELDS.has(f)).sort(),
    notAllowed: [...ALL_TASK_FIELDS].filter(f => !ALLOWED_TASK_FIELDS.has(f)).sort(),
    allowedCount: allowed.length,
    specCount: ALL_TASK_FIELDS.size,
  };
}

export function crossCheckTriggerFields(): CrossCheck {
  const allowed = [...ALLOWED_TRIGGER_FIELDS];
  return {
    notInSpec: allowed.filter(f => !ALL_TRIGGER_FIELDS.has(f)).sort(),
    notAllowed: [...ALL_TRIGGER_FIELDS].filter(f => !ALLOWED_TRIGGER_FIELDS.has(f)).sort(),
    allowedCount: allowed.length,
    specCount: ALL_TRIGGER_FIELDS.size,
  };
}

/** Validates a generated payload's field names against the spec for its type. */
export function validatePayloadFields(
  payload: Record<string, unknown>,
  kind: 'task' | 'trigger',
  type: string,
): { unknown: string[]; checked: number; typeKnown: boolean } {
  const fields = kind === 'task' ? taskFields(type) : triggerFields(type);
  if (fields.length === 0) return { unknown: [], checked: 0, typeKnown: false };
  const set = new Set(fields);
  return {
    unknown: Object.keys(payload).filter(k => !set.has(k)),
    checked: Object.keys(payload).length,
    typeKnown: true,
  };
}

// ── Knowledge chunks ─────────────────────────────────────────────────────────

/**
 * Chunks grounded in the controller spec rather than in our own prose. These let
 * the Copilot answer "is X a real field?" and "which endpoints exist?" from the
 * vendor's definition instead of our summary of it.
 */
export const UAC_SCHEMA_CHUNKS: KnowledgeChunk[] = [
  {
    id: 'uac.spec.overview',
    kind: 'integration',
    title: `UAC REST API surface (controller ${CONTROLLER_VERSION})`,
    pages: ['configuration', 'execution', 'job-creation'],
    keywords: ['openapi', 'rest api', 'controller version', 'uac endpoints', 'spec', 'resources'],
    source: 'openapi.json via backend/scripts/extract-uac-schema.cjs',
    body: `The target controller exposes ${UAC_SCHEMA.endpoints.length} REST endpoints, taken from its own OpenAPI ${UAC_SCHEMA.openapi} specification for version ${CONTROLLER_VERSION}.

The ones this application uses: /resources/task (read and create), /resources/trigger (read, create, enable), /resources/agent and /resources/agentcluster (list, suspend, resume), /resources/taskinstance (status and operations), and the trigger qualifying-times query.

Field names are validated against this spec, not against a hand-maintained list, so "is this a real UAC field?" is answered from the vendor definition. ${Object.keys(UAC_SCHEMA.tasks).length} task types and ${Object.keys(UAC_SCHEMA.triggers).length} trigger types are indexed.`,
  },
  {
    id: 'uac.spec.task-fields',
    kind: 'field',
    title: 'How many fields each UAC task type accepts',
    pages: ['preview', 'validation', 'search'],
    keywords: ['task fields', 'how many fields', 'schema', 'valid fields', 'taskUnix fields'],
    source: 'openapi.json',
    body: `Field counts per task type on controller ${CONTROLLER_VERSION}:
${Object.entries(UAC_SCHEMA.tasks).map(([k, v]) => `${k}: ${v.fields.length} fields (schema ${v.schema})`).join('\n')}

A task inherits most of its fields from shared ancestors, which is why the counts are similar: the distributed-agent types add agent and command handling, the monitor types add their own trigger conditions.

This application deliberately sends only a small subset. Everything not on the allow-list in payloadMapper is stripped before the request, so an unrecognised spreadsheet column never reaches the controller.`,
  },
  {
    id: 'uac.spec.trigger-fields',
    kind: 'field',
    title: 'Fields the UAC time trigger accepts',
    pages: ['preview', 'validation', 'scheduling'],
    keywords: ['trigger fields', 'triggerTime fields', 'schema', 'valid trigger fields'],
    source: 'openapi.json',
    body: `The time trigger (schema ${UAC_SCHEMA.triggers.triggerTime?.schema}) accepts ${UAC_SCHEMA.triggers.triggerTime?.fields.length} fields on controller ${CONTROLLER_VERSION}.

Other trigger types the controller supports: ${Object.keys(UAC_SCHEMA.triggers).filter(t => t !== 'triggerTime').join(', ')}. This application creates time triggers only — the others must be built in the UAC interface.

The scheduling fields that matter are timeStyle, time, timeInterval, timeIntervalUnits, timeZone, dayStyle, simpleDateType, the individual day flags, businessDays, and the dateAdjective / dateNouns / dateQualifiers set used for formula patterns.`,
  },
];
